### ISSUE TITLE
AI cutting itself off mid message? 

### ISSUE THREAD

**Issue by hyosettsu** [TavernAI/TavernAI#65]
I'm writing a pretty action-heavy convo - like 50-60 tokens of action in asterisks, usually followed by a sentence or two of dialogue per message. But Tavern is having a LOT of issues with message formatting. Every single message for the past 20 or so AI replies have all been messed up... either cut off mid-sentence, leave off an asterisk on the actions, adding unnecessary line breaks, or even starts generating replies for me? I've spent a long time tweaking settings, and I've even tried starting a new chat, but it hasn't helped at all. I edit the AI generated replies every time, but it keeps doing it. My amount generation is pretty cranked, so I have no idea why it keeps cutting itself off and messing up formatting. I'm extremely consistent with my formatting style. Does anyone know how to fix this?

**Comment by v1rus69** [comment]
I'm getting this as well. have you found a fix? Anyone else having this issue?

**Comment by hyosettsu** [comment]
@v1rus69 Someone on reddit actually helped me fix this! The issue for me was I had chat mode toggled on. Apparently it can happen if you have either chat mode/adventure mode on. As soon as I toggled chat mode off. It seemed to fix itself! It still cuts off messages once in a while, but it's not happening every single message like before. I hope it works for you too!
